# Changes here will be overwritten by Copier
_commit: e730ed7
_src_path: gh:audivir/copier-template
author_email: pypi@audivir.de
author_name: Tim Hörmann
description: Reader and writer for ReliableTXT UTF-8 text files
github_org: audivir
project_name: reliabletxt
project_slug: reliabletxt
project_type: pyo3
publishable: false
