[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "reliabletxt"
dynamic = ["version"]
description = "Reader and writer for ReliableTXT UTF-8 text files"
authors = [{ name = "Tim Hörmann", email = "pypi@audivir.de" }]
readme = "README.md"
requires-python = ">=3.10,<3.15"
license = "MIT"
keywords = []
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Typing :: Typed",
  "Programming Language :: Rust",
]
dependencies = []

[project.optional-dependencies]

[project.urls]
Homepage = "https://github.com/audivir/reliabletxt"
Repository = "https://github.com/audivir/reliabletxt"
Issues = "https://github.com/audivir/reliabletxt/issues"

[dependency-groups]
dev = ["mypy", "pytest", "coverage", "prek", "ruff"]

[tool.maturin]
python-source = "python"
module-name = "reliabletxt._reliabletxt"

[tool.mypy]
strict = true
disable_error_code = "import-untyped"
enable_error_code = """type-arg,no-untyped-def,redundant-cast,redundant-self,comparison-overlap,
                    no-untyped-call,no-any-return,no-any-unimported,unreachable,deprecated,redundant-expr,
                    possibly-undefined,truthy-bool,truthy-iterable,ignore-without-code,
                    unused-awaitable,unused-ignore,explicit-override,unimported-reveal,mutable-override,explicit-any"""

# beyond strict
warn_unreachable = true
warn_unused_configs = true
local_partial_types = true

exclude = ["build", "docs"]

[tool.coverage.run]
source = ["tests", "reliabletxt"]
command_line = "-m pytest"
branch = true
patch = ["subprocess"]

[tool.coverage.report]
omit = ["_types.py", "tests/benchmark.py"]
exclude_also = [
  "if TYPE_CHECKING:",
  'if __name__ == "__main__"',
  "from __future__ import annotations",
  "@overload",
  "\\.\\.\\.",
]
fail_under = 100
show_missing = true

[tool.pytest.ini_options]
minversion = "8.0"
addopts = ["-ra", "--showlocals", "--strict-markers", "--strict-config"]
xfail_strict = true
log_cli_level = "INFO"
filterwarnings = [
  "error",
  "ignore::pytest.PytestCacheWarning",
  "ignore::DeprecationWarning",
]
testpaths = ["tests"]

[tool.vulture]
ignore_names = ["_*", "unused_*"]
paths = [".whitelist", "tests", "python"]
make_whitelist = true
sort_by_size = true
verbose = false

[tool.ruff]
line-length = 100

[tool.ruff.lint]
dummy-variable-rgx = "^(dummy_.*|unused_.*|_)$"

select = ["ALL"]

ignore = [
  "CPY001",  # Missing copyright notice at top of file
  "PLC0415", # `import` should be at the top-level of a file
  "ISC001",  # implicit-str-concat
  "COM812",  # missing-trailing-comma
  "S301",    # `pickle` and modules that wrap it can be unsafe when used to deserialize untrusted data, possible security issue
  "TD003",   # Missing issue link on the line following this TODO
  "FIX002",  # Line contains TODO, consider resolving the issue
  "FBT001",  # Boolean-typed positional argument in function definition
  "FBT002",  # Boolean default positional argument
  "FBT003",  # Boolean positional value in function call
  "ANN401",  # Dynamically typed expressions (typing.Any) are disallowed in `**kwargs`
  "EM101",   # Exception must not use a string literal, assign to variable first
  "EM102",   # Exception must not use an f-string literal, assign to variable first
  "TRY003",  # Avoid specifying long messages outside the exception class
  "TRY300",  # Use of else blocks in try/except
  "D105",    # Missing docstring in magic method
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.isort]
required-imports = ["from __future__ import annotations"]
split-on-trailing-comma = false

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.per-file-ignores]
# Stub files for C extensions are allowed to have docstrings and overwrite __doc__, __version__, etc.
"_*.pyi" = ["PYI021", "A"]

# conf.py automatically created by Sphinx
"docs/conf.py" = ["INP001", "D100", "ERA001", "A"]

# Test files do not need to have docstrings at each test function
# S101: assert, PLR2004: magic value comparison, T20: print statements
"**/test_*.py" = ["INP001", "PLR2004", "S101", "D101", "D102", "D103", "T20"]
"tests/**" = ["INP001", "PLR2004", "S101", "D101", "D102", "D103", "T20"]
